### ISSUE TITLE
How are attachments handled?

### ISSUE THREAD

**Issue by digilord** [nodejitsu/txn#7]
I am writing an application that pulls an attachment from a CouchDB document, writes it to disk, manipulates it, then stores the resultant document(s) back into CouchDB. The first part works brilliantly.  No issues getting the attachment, writing it to disk and manipulating it.

To replicate the error below you need the following:
- A CouchDB server running somewhere or access to one.
- A database named presentations
- A document in said database.
- A directory named for the _id of the document in presentations
- A PNG in said directory.
- Node modules
  - fs
  - path
  - mime
  - glob
  - txn

Change the location of _workdir to match where you created the directory.

Save the program as `uploadPNG.js`. Run with this command 

`./uploadPNG.js --id directoryName`.  

It is supposed to go through and add all the files to the CouchDB document that has the same ID as the directory.  The below code does in fact pull the document.  It just doesn't add the attachments and I am not sure why. Here is the resultant error from running the program.

Can anyone help me get this working like I think it should?

---
## Error

```
{ [Error: CouchDB error: {"error":"unknown_error","reason":"function_clause"}]
  statusCode: 500,
  error: 'unknown_error',
  reason: 'function_clause' }

Error: CouchDB error: {"error":"unknown_error","reason":"function_clause"}
    at /Users/digilord/projects/superslick/couch_worker/node_modules/txn/lib/lib.js:59:18
    at Request._callback (/Users/digilord/projects/superslick/couch_worker/node_modules/txn/lib/lib.js:125:12)
    at Request.self.callback (/Users/digilord/projects/superslick/couch_worker/node_modules/txn/node_modules/request/index.js:142:22)
    at Request.EventEmitter.emit (events.js:98:17)
    at Request.<anonymous> (/Users/digilord/projects/superslick/couch_worker/node_modules/txn/node_modules/request/index.js:856:14)
    at Request.EventEmitter.emit (events.js:117:20)
    at IncomingMessage.<anonymous> (/Users/digilord/projects/superslick/couch_worker/node_modules/txn/node_modules/request/index.js:808:12)
    at IncomingMessage.EventEmitter.emit (events.js:117:20)
    at _stream_readable.js:895:16
    at process._tickCallback (node.js:415:13)
```

---
## uploadPNG.js

```
#!/usr/bin/env node
var fs = require('fs'),
    path = require('path'),
    mime = require('mime'),
    glob = require("glob");

var txn = require('txn').defaults({"timestamps":true, "couch":"http://localhost:5984"});
var presentations_txn = txn.defaults({"db":"presentations", "delay":1000, "timeout":30000});


var argv = require('optimist')
    .usage('Usage: $0 --id [Document ID]')
    .demand(['id'])
    .argv;

var _doc_id = argv.id;

var _workdir = path.join(path.resolve('/Volumes/ramdisk'), 'work');
var _docdir = path.join(_workdir, _doc_id);

var _doc = null

var addAttachments = function(doc, to_txn){
    console.log(doc);
    console.log('Initial document fetched for: ', doc._id);
    console.log('Ready to push files to CouchDB for: ', _doc_id);

    var _globPattern = _docdir + '/*.png';
    var _pngs = glob.sync(_globPattern);
    // console.log('PNGs: ', _pngs);

    _pngs.forEach(function(_file){
        var _filecontents = fs.readFileSync(_file);
        var _mime_type = mime.lookup(_file);
        var _filename = _file.split('/').pop();

        console.log("Processing Attachment: ", _filename)
        if(typeof doc._attachments[_filename] == 'object'){
            doc._attachments[_filename].content_type = _mime_type;
            doc._attachments[_filename].body = _filecontents;
        } else {
            doc._attachments[_filename] = {};
            doc._attachments[_filename].content_type = _mime_type;
            doc._attachments[_filename].body = _filecontents;
        }
        // uploadAttachment(_file, _docdir, _doc_id)
    });
    doc.processed = true;
    to_txn()
}

presentations_txn({"id": _doc_id}, addAttachments, function(error, newData) {
  if(!error)
    return console.log("Processed " + _doc_id + " to state: " + newData.processed);

  // These errors can be sent by Txn.
  if(error.timeout)
    return console.log("Gave up after MANY conflicts");
  if(error.conflict)
    return console.log("addAttachments never completed. Troubleshoot and try again");

  console.log(error);
  throw error; // Unknown error
});
```

**Comment by digilord** [comment]
Solved via http://stackoverflow.com/questions/18945757/uploading-attachments-to-couchdb-with-txn-in-node-js-problems
